name=moddoMOUSE
version=0.2.0
author=moddo inc.
maintainer=moddo inc. <info@moddo.io>
sentence=Allows you to communicate with the moddoMOUSE main board from your Arduino on an expansion board
paragraph=
category=Device Control
url=https://github.com/moddoio/moddoMOUSE-Arduino
architectures=*
includes=moddoMOUSE.h
